### ISSUE TITLE
SedML script error: app2sim

### ISSUE THREAD

**Issue by 0u812** [sys-bio/sedml2py#3]
Conversion to Python works but Python script cannot be run. Error message is:

```
NameError: name 'dataGen_task_0_0_s0' is not defined
```

**Comment by 0u812** [comment]
Imported script:
```
# -*- coding: utf-8 -*-

"Generated by Import SED-ML plugin 08/26/2015"
"Extracted from app2sim.sedml"

# Translated SED-ML
# Beginning of generated script
import roadrunner
import numpy as np
import matplotlib.pyplot as plt

# Execute the tasks of model: Application0
Application0 = roadrunner.RoadRunner()
Application0.load('/Users/phantom/devel/src/sedml2py/testing/app2sim/BioModel1_Application0.xml')
Application0.selections = ["time","s0","s1"]
t_0_0 = Application0.simulate(0, 20, 1000)

# Execute the tasks of model: Application0_0
Application0_0 = roadrunner.RoadRunner()
Application0_0.load('/Users/phantom/devel/src/sedml2py/testing/app2sim/BioModel1_Application0.xml')
Application0_0.model["init([s1])"] = 10.0
Application0_0.selections = ["time","s0","s1"]
t_0_1 = Application0_0.simulate(0, 30, 1000)

# List of Data Generators
time_t_0_0 = t_0_0[0.0:,0]
dGen_t_0_0_s0 = t_0_0[0.0:,1]
dGen_t_0_0_s1 = t_0_0[0.0:,2]

time_t_0_1 = t_0_1[0.0:,0]
dGen_t_0_1_s0 = t_0_1[0.0:,1]
dGen_t_0_1_s1 = t_0_1[0.0:,2]

# List of Outputs
Y_0 = np.array([dataGen_task_0_0_s0, dataGen_task_0_0_s1]).T
plt.plot(time_task_0_0, Y_0)
plt.title('Application0plots')
plt.show()

Y_1 = np.array([dataGen_task_0_1_s0, dataGen_task_0_1_s1]).T
plt.plot(time_task_0_1, Y_1)
plt.title('Application0plots')
plt.show()

# End of generated script

```

**Comment by 0u812** [comment]
Full trace:
```
Traceback (most recent call last):

  File "<ipython-input-10-0bd1405db215>", line 1, in <module>
    runfile('/Users/phantom/Documents/tmp/app2sim_sedml.py', wdir='/Users/phantom/Documents/tmp')

  File "/Volumes/Tellurium-1.2.4-Spyder-2.3.5.2-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "/Volumes/Tellurium-1.2.4-Spyder-2.3.5.2-OSX/Spyder-Py2.app/Contents/Resources/lib/python2.7/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/Users/phantom/Documents/tmp/app2sim_sedml.py", line 35, in <module>
    Y_0 = np.array([dataGen_task_0_0_s0, dataGen_task_0_0_s1]).T

NameError: name 'dataGen_task_0_0_s0' is not defined
```

Running this on Mac Tellurium.

**Comment by 0u812** [comment]
# Different error on Windows:
```
Traceback (most recent call last):

  File "<ipython-input-1-d1623e2da156>", line 1, in <module>
    runfile('C:/Users/phantom/Documents/tmp/app2sim_sedml.py', wdir='C:/Users/phantom/Documents/tmp')

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 711, in runfile
    execfile(filename, namespace)

  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 79, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/phantom/Documents/tmp/app2sim_sedml.py", line 26, in <module>
    time_t_0_0 = t_0_0[0.0:,0]

IndexError: too many indices for array
```

# Generated file on Windows:
```
# -*- coding: utf-8 -*-

"Generated by Import SED-ML plugin 08/26/2015"
"Extracted from app2sim.sedml"

# Translated SED-ML
# Beginning of generated script
import roadrunner
import numpy as np
import matplotlib.pyplot as plt

# Execute the tasks of model: Application0
Application0 = roadrunner.RoadRunner()
Application0.load('C:/Users/phantom/Documents/devel/src/sedml2py/testing/app2sim/BioModel1_Application0.xml')
Application0.selections = ["time","s0","s1"]
t_0_0 = Application0.simulate(0, 20, 1000)

# Execute the tasks of model: Application0_0
Application0_0 = roadrunner.RoadRunner()
Application0_0.load('C:/Users/phantom/Documents/devel/src/sedml2py/testing/app2sim/BioModel1_Application0.xml')
Application0_0.model["init([s1])"] = 10.0
Application0_0.selections = ["time","s0","s1"]
t_0_1 = Application0_0.simulate(0, 30, 1000)

# List of Data Generators
time_t_0_0 = t_0_0[0.0:,0]
dGen_t_0_0_s0 = t_0_0[0.0:,1]
dGen_t_0_0_s1 = t_0_0[0.0:,2]

time_t_0_1 = t_0_1[0.0:,0]
dGen_t_0_1_s0 = t_0_1[0.0:,1]
dGen_t_0_1_s1 = t_0_1[0.0:,2]

# List of Outputs
Y_0 = np.array([dGen_t_0_0_s0, dGen_t_0_0_s1]).T
plt.plot(time_t_0_0, Y_0)
plt.title('Application0plots')
plt.show()

Y_1 = np.array([dGen_t_0_1_s0, dGen_t_0_1_s1]).T
plt.plot(time_t_0_1, Y_1)
plt.title('Application0plots')
plt.show()

# End of generated script

```

**Comment by 0u812** [comment]
To reproduce, just do File->Import->Import SED-ML and select app2sim.sedml

**Comment by kirichoi** [comment]
Windows error is not reproducible. Could you check the dimension of t_0_0  and t_0_1?

**Comment by 0u812** [comment]
```
print(t_0_0.shape)
print(t_0_1.shape)
```
(1000,)
(1000,)

**Comment by 0u812** [comment]
Resolved Windows error: was due to my RR config file.

**Comment by kirichoi** [comment]
Retried using the updated version of libSEDML. The problem shown in Mac OS is not reproducible on Windows so it is not related to libraries.

**Comment by 0u812** [comment]
I found the problem. You had uncommitted changes you were shipping with Windows Tellurium that were not present in your master branch. I copied them over Please ensure all changes you intend to ship are committed in the future in order to avoid cases like this.

**Comment by kirichoi** [comment]
Sorry for that. Might have pushed to my fork but not to the master.
